name: pl_tracker_v1
services:
  db:
    image: postgres:16
    container_name: pl_db_v1
    environment:
      POSTGRES_USER: pl_user
      POSTGRES_PASSWORD: pl_pass
      POSTGRES_DB: pl_tracker_v1
    ports:
      - "5541:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: pl_adminer_v1
    ports:
      - "8089:8080"

volumes:
  dbdata:
