spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pl_tracker
    username: pl_user
    password: pl_pass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
