spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pl_tracker
    username: pl_user
    password: pl_pass
  jpa:
    hibernate:
      ddl-auto: validate   # checks your existing tables; doesn't create them
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never          # we’re not using Spring to run schema/seed
server:
  port: 8080
